[package]
name = "rdu"
version = "1.0.0"
authors = ["agraham <andrew.t.graham@live.com>", "Joshua Sleeper <joshua.sleeper+github@gmail.com>"]
description = "A fast(er) du ASCII visualizer written in Rust."
license = "MIT"

[dependencies]
clap = "2.32.0"
